sudo: required
dist: trusty

language: generic

install:
  #install Lua 5.3 (not in Ubuntu repositories yet)
  wget http://www.lua.org/ftp/lua-5.3.1.tar.gz
  tar xzf lua-5.3.1.tar.gz
  cd lua-5.3.1.tar.gz
  make linux
  sudo make install

  sudo apt-get install lua5.2 lua5.1 luajit luarocks

  sudo luarocks install busted

script:
  for lua in /usr/bin/lua*
  do
    busted --lua=$lua spec
  done
